# Generated by Django 5.0.1 on 2024-02-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Accounts',
        ),
    ]
