# Generated by Django 5.0.1 on 2024-02-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscribers'},
        ),
        migrations.AlterModelTable(
            name='subscribers',
            table=None,
        ),
    ]
