# Generated by Django 5.0.1 on 2024-02-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_options_alter_subscribers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
