# Generated by Django 5.0.1 on 2024-01-29 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_base_price', models.IntegerField()),
                ('product_discounted_price', models.IntegerField()),
                ('in_stock', models.BooleanField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='product.details', to_field='name')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.tag', to_field='name')),
            ],
        ),
    ]
