# Generated by Django 5.0.1 on 2024-02-13 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_product_category_subcategorya_subcategoryb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategorya'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryb'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
