# Generated by Django 5.0.1 on 2024-02-15 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_subcategory_a_product_subcategory_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product-Images'},
        ),
        migrations.AlterModelOptions(
            name='subcategorya',
            options={'verbose_name_plural': 'SubCategory A'},
        ),
        migrations.AlterModelOptions(
            name='subcategoryb',
            options={'verbose_name_plural': 'SubCategory B'},
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategorya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryb'),
        ),
    ]
