# Generated by Django 5.0.1 on 2024-02-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_name_alter_subcategorya_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryb',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
