# Generated by Django 5.0.1 on 2024-02-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='account.account')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_id', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
